### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DevilHevo** [AndreTkachenkoOrg/lfg-bot#47]
Error

It seems you faced some issues when tried to create event:
 Took to long to respond.

it doesen't give us anytime to make the ticket it closes it asap after u type lfg start.

**Comment by dreytko** [comment]
Hello @DevilHevo 
Let me check it real quick

**Comment by dreytko** [comment]
@DevilHevo I've fixed it, could you please try create event again?

**Comment by DevilHevo** [comment]
it still has some troubles when i type it like that that's how it pops the
lfg msg

**Comment by dreytko** [comment]
Hello @DevilHevo 
I didn't quite get what exactly is the problem that you're facing.
But while testing the bot I found out that it works kind of strange with description/when questions and answers.
I've deployed the fix. If this is a problem you were talking about - that's great, otherwise could you please provide a more detailed description of the problem?
