### ISSUE TITLE
Edit survey questions

### ISSUE THREAD

**Issue by ChrisCartagena** [AndreTkachenkoOrg/lfg-bot#54]
It would be a really awesome feature if the questions the Bot ask during the survey could be changed, this would allow for any types of servers to use the bot and change the questions to their needs.

**Comment by dreytko** [comment]
Hello @ChrisCartagena 
Thank you for the feedback.
This idea has already been appearing in my mind, plus it was raised as a ticket once (#36).
For now, adding optional/server-specific questions was not created due to performance considerations.
You are welcome to suggest a different set of questions that you think should be in the survey, I'd gladly consider feedback from the bot's user.

Also, just for more clarity - could you please add more specifics what is your case to be in the need of different/additional questions? I've tried to make questions quite generic exactly to be able to be used not for just games, but for other activities as well. If you provide a bit more info about your specific vision of the survey I might as well reconsider optional questions implementation.

**Comment by dreytko** [comment]
Closed due to inactivity.
Consider reopening this ticket in case you want to resume the conversation
