### ISSUE TITLE
Survey channel does not sync with category permissions

### ISSUE THREAD

**Issue by Chillidaddy** [AndreTkachenkoOrg/lfg-bot#63]
lfg start - created survey channel does not honor/sync category permissions.

**Comment by sprinterra-andrey-tkachenko** [comment]
Hello @Chillidaddy 
It was never intended to work that way.
Anyhow, I'm sorry but I'm unable to take a look at this in foreseeable future - I'm from Ukraine.
Maybe I will be able to return to this when the war is over.
God bless you!

**Comment by dreytko** [comment]
Hello @Chillidaddy
It was never intended to work that way.
Anyhow, I'm sorry but I'm unable to take a look at this in foreseeable future - I'm from Ukraine.
Maybe I will be able to return to this when the war is over.
I wish you the best of luck in these times!

**Comment by Chillidaddy** [comment]
> Hello @Chillidaddy It was never intended to work that way. Anyhow, I'm sorry but I'm unable to take a look at this in foreseeable future - I'm from Ukraine. Maybe I will be able to return to this when the war is over. I wish you the best of luck in these times!

@andretkachenko Oh no :(( I'm so sorry, I hope this unnecessary war will be over soon. Wish you and your family the best of luck. Stay strong brother

**Comment by dreytko** [comment]
Thank you for your support

**Comment by dreytko** [comment]
Hello @Chillidaddy 
Hope you are doing well.
While the war is still going on, I've returned back home, so I can continue this postponed conversation.
I've already written that it was not intended to work this way, but now I would like to give you some explanation for it:
All users are able to see the survey channel because I wanted to give bot users the freedom to ping any server user - it's in the nature of discord itself that you can only ping people who can see the channel where you're pinging them.
If that's what you're talking about - well, there are possible solutions to make any changes to existing rules, but that can bring unexpected behaviour also, so we can discuss how you see survey channel permissions configuration.
If you're talking about some different permissions - please provide more info and I will see what I can do with it.
